version: '3.9'
services:
  node_service:
    container_name: node_16_container
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/workspaces/node-16-setup
